#!/bin/bash
virtualenv env
source env/bin/activate
pip install -r requirements/common.txt
pip install -r requirements/dev.txt
pip install -r requirements/production.txt
git submodule init
git submodule update
export DEPLOYMENT_TYPE=DEV
